// <auto-generated />
using System;
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GliceControl.Infra.Migrations
{
    [DbContext(typeof(GliceControlContext))]
    [Migration("20240827172236_m0")]
    partial class m0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Domain.Entities.ControleGlicemico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("Periodo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValorGlicemico")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ControleGlicemico");
                });
#pragma warning restore 612, 618
        }
    }
}
